### ISSUE TITLE
[PE-D] Edit command format is not in sync with the rest of the commands.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103T-W13-1/tp#203]
The command to edit clients is just `edit`. This does not fit well with the rest of the commands where the CRUD commands have either a `Proc` or a `Client` in front of them. 

I believe that if the command is titled as `editClient`, it would mesh well with the other commands.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: eman-kom/ped#22

**Comment by aceszhenwei** [comment]
Cannot edit due to feature freeze
